from datetime import datetime
from typing import Protocol
from uuid import UUID

from newsbot.domain.enums import StoryStatus
from newsbot.domain.models import (
    Article,
    CouncilVoteRecord,
    PostedTweet,
    RejectionRecord,
    Source,
    Story,
)


class SourceRepository(Protocol):
    async def list_active(self) -> list[Source]: ...

    async def mark_polled(self, source_id: UUID, when: datetime) -> None: ...

    async def get_by_id(self, source_id: UUID) -> Source | None: ...


class ArticleRepository(Protocol):
    async def exists(self, source_id: UUID, external_id: str) -> bool: ...

    async def add(self, article: Article) -> Article: ...

    async def update_embedding(self, article_id: UUID, embedding: list[float]) -> None: ...

    async def list_unclustered(self, since: datetime) -> list[Article]: ...

    async def attach_to_story(self, article_id: UUID, story_id: UUID) -> None: ...

    async def list_by_story(self, story_id: UUID) -> list[Article]: ...


class StoryRepository(Protocol):
    async def add(self, story: Story) -> Story: ...

    async def get(self, story_id: UUID) -> Story | None: ...

    async def find_similar(
        self, embedding: list[float], since: datetime, limit: int = 5
    ) -> list[tuple[Story, float]]: ...

    async def update_status(self, story_id: UUID, status: StoryStatus) -> None: ...

    async def set_breaking(self, story_id: UUID, is_breaking: bool) -> None: ...

    async def set_category(self, story_id: UUID, category: str) -> None: ...

    async def update_scores(
        self, story_id: UUID, confidence_score: float | None = None, importance_score: float | None = None
    ) -> None: ...

    async def list_by_status(self, status: StoryStatus, limit: int = 50) -> list[Story]: ...

    async def increment_source_count(self, story_id: UUID, similarity_score: float, article_id: UUID) -> None: ...


class TweetRepository(Protocol):
    async def add(self, tweet: PostedTweet) -> PostedTweet: ...

    async def count_since(self, since: datetime) -> int: ...

    async def last_posted_at(self) -> datetime | None: ...

    async def list_recent(self, limit: int = 50) -> list[PostedTweet]: ...


class RejectionRepository(Protocol):
    async def add(self, rejection: RejectionRecord) -> RejectionRecord: ...

    async def list_recent(self, limit: int = 100) -> list[RejectionRecord]: ...


class CouncilVoteRepository(Protocol):
    async def add(self, vote: CouncilVoteRecord) -> CouncilVoteRecord: ...

    async def list_for_story(self, story_id: UUID) -> list[CouncilVoteRecord]: ...
